# Developed by Eng. Mouaz M. Al-Shahmeh
name: bosra_elcham
description: Developed by Eng Mouaz M AlShahmeh
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.9
  cloud_firestore: ^4.13.3
  cached_network_image: ^3.3.0
  firebase_core: ^2.24.0
  google_fonts: ^6.1.0
  go_router: ^12.1.1
  http: ^1.1.2
  webview_flutter: ^4.4.2
  photo_view: ^0.14.0
  wakelock_plus: ^1.1.4
  audioplayers: ^5.2.1
  connectivity_plus: ^5.0.2
  another_flutter_splash_screen: ^1.2.0
  url_launcher: ^6.2.1
  firebase_crashlytics: ^3.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/music.mp3
    - assets/langs/
    - assets/images/
